// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import React from 'react';
import { Link } from 'react-router-dom';
import './css/style.css';
import './css/utilities.css';
/**
 * This component is used to display the required
 * privacy statement which can be found in a link in the
 * about tab.
 */
class Privacy extends React.Component {
  render() {
    return (
      <div className='privacy'>
        {/* Navbar */}
        <div class="navbar">
          <div class="container flex">
            <h1 class="logo">Expense Claim</h1>
            <nav>
              <ul>
                <li><Link to="/">Home</Link></li>
                <li><Link to="/privacy">Privacy</Link></li>
                <li><Link to="/termsofuse">Terms of Use</Link></li>
              </ul>
            </nav>
          </div>
        </div>

        {/* Privacy */}
        <section class="privacy-text">
          <div class="container">
            <h1>Privacy Policy</h1>



            <p>Updated: July 1, 2023</p>



            <p>The Privacy Policy presented here elaborates on the collection, usage, and disclosure of your information during the use of the Expense Claim Application. It outlines your privacy rights and how they're protected under the law.</p>



            <p>Your Personal Data is used to deliver and enhance the Expense Claim Application. By utilizing the Expense Claim Application, you consent to the data collection and its use in agreement with this Privacy Policy.</p>



            <h2>Interpretation and Definitions</h2>



            <h3>Interpretation</h3>



            <p>Words with initial capital letters in this Privacy Policy have specific meanings defined under the respective conditions. The definitions apply regardless of whether they appear in singular or plural forms.</p>



            <h3>Definitions</h3>



            <p>In the context of this Privacy Policy:</p>



            <ul>

              <li>Account refers to a unique account established for your access to the Expense Claim Application or its components.</li>

              <li>Affiliate indicates an entity that has control over, is controlled by, or shares common control with a party, where "control" signifies owning 50% or more of the voting shares, equity interest, or other securities eligible to vote for the election of directors or other managing authority.</li>

              <li>Application refers to the software program, Expense Claim, provided by the Company, which can be downloaded on any electronic device.</li>

              <li>Company (also referred to as "We", "Us", or "Our") pertains to Reliance Infosystems Limited.</li>

              <li>Country points to Nigeria.</li>

              <li>Device encompasses any electronic device that can access the Expense Claim Application, such as a computer, a cellphone, or a digital tablet.</li>

              <li>Personal Data pertains to any information relating to an identified or identifiable individual.</li>

              <li>Service is equivalent to the Application.</li>

              <li>Service Provider indicates any person or entity processing the data on behalf of the Company. It includes third-party companies or individuals engaged by the Company to facilitate the Expense Claim Application, provide the Application on behalf of the Company, perform related services, or assist the Company in analyzing the Application usage.</li>

              <li>Usage Data refers to automatically collected data, either generated by using the Expense Claim Application or from the Application infrastructure itself (e.g., duration of a page visit).</li>

              <li>You refer to the individual accessing or using the Expense Claim Application, or the company or other legal entity on whose behalf such individual is accessing or using the Application.</li>

            </ul>



            <h2>Collection and Usage of Your Personal Data</h2>



            <h3>Types of Data Collected</h3>



            <p><strong>Personal Data</strong></p>



            <p>While using the Expense Claim Application, we may have access to certain personally identifiable information, which may include, but is not limited to:</p>



            <ul>

              <li>Email address</li>

              <li>First name and last name</li>

              <li>Phone number</li>

              <li>Address, State, Province, ZIP/Postal code, City</li>

            </ul>



            <p><strong>Usage Data</strong></p>



            <p>Usage Data is collected automatically when the Expense Claim Application is used. It may include your Device's IP address, browser type, browser version, pages visited in the Application, time and date of your visit, time spent on those pages, unique device identifiers, and other diagnostic data.</p>



            <h3>Use of Your Personal Data</h3>



            <p>We may use Personal Data for the following purposes:</p>



            <ul>

              <li>To deliver and monitor the Expense Claim Application.</li>

              <li>To manage your Account: Your Personal Data enables access to different functionalities of the Application available to registered users.</li>

              <li>To contact you via email, telephone calls, SMS, or other forms of electronic communication.</li>

              <li>To manage your requests made to Us.</li>

              <li>For business transfers: Your information may be used to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of our assets.</li>

            </ul>



            <p>We may share your personal information under these circumstances:</p>



            <ul>

              <li>With Service Providers: To monitor and analyze the use of the Expense Claim Application or to contact You.</li>

              <li>For business transfers: In connection with a merger, sale of Company assets, financing, or acquisition of all or a part of Our business to another company.</li>

              <li>With Affiliates: To share Your information with Our affiliates, ensuring they honor this Privacy Policy.</li>

            </ul>



            <h2>Retention of Your Personal Data</h2>



            <p>We will retain your Personal Data as long as necessary for the purposes set out in this Privacy Policy, complying with our legal obligations, resolving disputes, and enforcing our legal agreements and policies. Usage Data will be retained for internal analysis purposes.</p>



            <h2>Transfer of Your Personal Data</h2>



            <p>Your information, including Personal Data, is processed at the Company's offices and wherever the processing parties are located. This could mean a transfer of information to computers located outside of your state, province, country, or other jurisdiction where data protection laws might differ. Your consent to this Privacy Policy symbolizes your agreement to such transfers.</p>



            <h2>Disclosure of Your Personal Data</h2>



            <p>Under specific circumstances, we may be obligated to disclose your Personal Data, for example, in response to valid requests by law enforcement or public authorities or to comply with a legal obligation.</p>



            <h2>Security of Your Personal Data</h2>



            <p>We strive to protect your Personal Data through commercially viable methods. However, the transmission of data over the Internet or electronic storage isn't 100% secure, and while we aim for utmost security, we can't guarantee it.</p>



            <h2>Links to Other Websites</h2>



            <p>The Expense Claim Application may contain links to other websites that we don't operate. Upon clicking a third-party link, you'll be redirected to their site. We strongly suggest reviewing the Privacy Policy of every site you visit.</p>



            <h2>Changes to this Privacy Policy</h2>



            <p>We may occasionally update our Privacy Policy. Changes will be effective when posted on this page, and while we may not provide individual notifications, we recommend reviewing this Privacy Policy periodically.</p>



            <h2>Contact Us</h2>



            <p>For any inquiries about this Privacy Policy, kindly reach out to support at be@relianceinfosystems.com</p>
          </div>
        </section>

        {/* Footer */}
        <footer className="footer">
          <div>
            <p><Link to="/privacy">Privacy Policy</Link></p>
            <p><Link to="/termsofuse">Terms of Use</Link></p>
            <p>&copy; Reliance Infosystems Limited</p>
          </div>
        </footer>

      </div>
    );
  }
}

export default Privacy;